services:

  mt5:
    image: hudsonventura/mt5:1.1
    build:
       context: ./
       dockerfile: ./Dockerfile

    ports:
      - "5901:5901" #VNC
      - "6901:6901" #noVNO (via browser: http://localhost:6901/vnc.html or http://localhost:6901/vnc.html?password=my_vnc_password)

    environment:
     - VNC_PW=my_vnc_password #VNC password. Change it as you like

    volumes:
      - ./.data/MQL5/:/home/headless/.wine/drive_c/Program Files/MetaTrader 5/MQL5/
      - ./mt5.ini:/home/headless/.wine/drive_c/Program Files/MetaTrader 5/mt5.ini
    #  - ./.data/MQL5/servers.dat:/home/headless/.wine/drive_c/Program Files/MetaTrader 5/Config/servers.dat # Uncomment if you ar using a non listed broker
      
    # Optional parameters:
    command: "/start.sh"       # If enabled, the container will shut down when MT5 is closed
    restart: always            # Automatically restarts the container if it stops
    mem_limit: 1536m           # Best practice. The container typically uses around 600MB

